# Generated by Django 4.1.7 on 2023-03-14 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=32, unique=True, verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('pwd', models.CharField(max_length=32, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工资余额')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], verbose_name='性别')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app02.department', to_field='department', verbose_name='部门')),
            ],
        ),
    ]
