# Generated by Django 4.1.7 on 2023-03-15 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 18, 29, 34, 976553), verbose_name='入职时间'),
        ),
    ]
