# Generated by Django 4.1.7 on 2023-03-15 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_employee_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='register_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='入职时间'),
        ),
    ]
