# Generated by Django 4.1.7 on 2023-03-22 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0004_admin_alter_account_level_alter_account_mobile_and_more'),
        ('app02', '0004_alter_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '普通'), (3, '临时')], verbose_name='级别')),
                ('detail', models.TextField(max_length=200, verbose_name='详细信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.admin', verbose_name='负责人')),
            ],
        ),
    ]
