# Generated by Django 3.2.18 on 2023-04-01 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0005_auto_20230330_0046'),
        ('app02', '0007_auto_20230331_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
                ('birthdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Birthdate')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('level', models.SmallIntegerField(choices=[(1, 'Platinum'), (2, 'Gold'), (3, 'Silver'), (4, 'Bronze')], verbose_name='Level')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.admin', verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=12, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=64, verbose_name='Order No.'),
        ),
    ]
