# Generated by Django 3.2.18 on 2023-04-01 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0008_auto_20230401_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.customer', verbose_name='Customer ID'),
        ),
    ]
