# Generated by Django 3.2.18 on 2023-04-04 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0009_alter_order_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthdate'),
        ),
    ]
