# Generated by Django 3.2.18 on 2023-04-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0011_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='pwd',
        ),
    ]
