# Generated by Django 4.1.7 on 2023-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(max_length=12, verbose_name='账号号码')),
                ('price', models.IntegerField(verbose_name='账号价格')),
                ('level', models.SmallIntegerField(choices=[(1, '至尊'), (2, '高级'), (3, '普通'), (4, '垃圾')], verbose_name='账号等级')),
                ('status', models.SmallIntegerField(choices=[(1, '占用'), (2, '未占用')], verbose_name='状态')),
            ],
        ),
    ]
