# Generated by Django 4.1.7 on 2023-03-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.IntegerField(verbose_name='账号号码'),
        ),
    ]
