# Generated by Django 4.1.7 on 2023-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_alter_account_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '至尊'), (2, '高级'), (3, '普通'), (4, '垃圾')], default=4, verbose_name='账号等级'),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='账号号码'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '占用'), (2, '未占用')], default=2, verbose_name='状态'),
        ),
    ]
