# Generated by Django 4.1.7 on 2023-03-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0003_alter_account_level_alter_account_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='管理员账号')),
                ('password', models.CharField(max_length=32, verbose_name='管理员密码')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '至尊'), (2, '高级'), (3, '普通'), (4, '垃圾')], default=4, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='account',
            name='price',
            field=models.IntegerField(verbose_name='价格'),
        ),
    ]
