# Generated by Django 3.2.18 on 2023-04-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0005_auto_20230330_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
